# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HURxSwiftNetWork' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxSwift', '~> 3.5.0'
  pod 'RxCocoa', '~> 3.5.0'
  pod 'Alamofire', '~> 4.5.0'
  pod 'SwiftyJSON', '~> 3.1.4'
  pod 'RxAlamofire', '~> 3.0.3'
  pod 'RxDataSources', '~> 1.0.4'
  pod 'MJRefresh', '~> 3.1.12'
  # Pods for HURxSwiftNetWork

end
