# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'HURxSwiftNetWork' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxSwift', '~> 4.0.0'
  pod 'RxCocoa', '~> 4.0.0'
#  pod 'Alamofire', '~> 4.5.0'
  pod 'SwiftyJSON', '~> 4.0.0-alpha.1'
#  pod 'RxAlamofire', '~> 3.0.3'
  pod 'RxDataSources', '~> 3.0.1'
  pod 'MJRefresh', '~> 3.1.14.1'
  pod 'Moya/RxSwift', '~> 10.0.0'
  # Pods for HURxSwiftNetWork

end
